Repository Manishak798/Dive-to-Dev_Hacktoberfest23, pull requests merged in 2023-10, with the labels that each got.

#5 I have made my contribution kindly review it.
  contributors.md
  images/project-images/Screenshot 2023-08-30 091509.png
  index.html
  script.js
Labels: good first issue, hacktoberfest

#6 Validating user input
  script.js
Labels: good first issue, hacktoberfest

#8 Create greetings.yml
  .github/workflows/greetings.yml
Labels: hacktoberfest

#9 Update README.md
  README.md
Labels: hacktoberfest

#11 Added Falling Blocks Game
  contributors.md
  images/project-images/FallingBlocks.png
  index.html
Labels: good first issue, hacktoberfest

#16 Weather app website
  images/project-images/Weather.jpeg
  index.html
Labels: good first issue, hacktoberfest

#15 Update style.css
  style.css
Labels: good first issue, hacktoberfest

#10 fixed overflow of row and made card width fixed in css
  index.html
  style.css
Labels: good first issue, hacktoberfest

#18 add new project
  contributors.md
  index.html
Labels: good first issue, hacktoberfest

#20 added a new project
  contributors.md
  images/project-images/apnaBazar.png
  index.html
Labels: good first issue, hacktoberfest

#21 Added Employee Directory to Projects
  images/project-images/EmoloyeeDirectoryScreenshot.png
  index.html
Labels: good first issue, hacktoberfest

#23 Added Slot Machine game project
  contributors.md
  images/project-images/SlotMachineSS.png
  index.html
Labels: good first issue, hacktoberfest

#29 Made the cards height align with each other
  index.html
  style.css
Labels: good first issue, hacktoberfest

#28 I have added my YouTube clone project
  index.html
Labels: good first issue, hacktoberfest

#31 fixing issue and added responsive design
  index.html
  style.css
Labels: good first issue, hacktoberfest

#32 task completed
  index.html
Labels: good first issue, hacktoberfest

#36 added ToDo list project
  images/project-images/ToDo list.png
  index.html
Labels: good first issue, hacktoberfest

#37 adding my web development project: google search engine clone
  contributors.md
  images/project-images/googleClone.jpg
  index.html
Labels: good first issue, hacktoberfest

#42 Add Pricing Panel Project
  images/project-images/hzshashwat.JPG
  index.html
Labels: good first issue, hacktoberfest

#38 add my drumkit project to index.html
  contributors.md
  images/project-images/drumkit-project.png
  index.html
Labels: good first issue, hacktoberfest

#48 Made logo and stylishing the navbar with responsiveness
  index.html
  script.js
  style.css
Labels: good first issue, hacktoberfest

#55 Added files for ToDo List App
  contributors.md
  images/project-images/ToDo_List.png
  index.html
Labels: good first issue, hacktoberfest

#57 Added Random_Quote_Generator
  contributors.md
  images/project-images/Random_Quote_Generator.png
  index.html
Labels: good first issue, hacktoberfest

#58 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement, good first issue, hacktoberfest

#60 Issue #53 Add logo in navbar.
  images/project-images/blog site.png
  images/project-images/logo.png
  images/project-images/youtube clone.png
  index.html
  style.css
Labels: enhancement, good first issue, hacktoberfest

#62 added notes web app
  contributors.md
  images/project-images/notes_taker.JPG
  index.html
Labels: hacktoberfest, Hacktoberfest-accepted

#63 I have added a Simple Bubble Game.
  images/project-images/bubble_game.png
  index.html
Labels: hacktoberfest, Hacktoberfest-accepted

#64 calender and footer added
  images/project-images/calendar.jpg
  index.html
Labels: enhancement, hacktoberfest, Hacktoberfest-accepted

#65 Ecommerce Added
  .vscode/settings.json
  contributors.md
  images/project-images/ecommerce.png
  index.html
Labels: hacktoberfest, Hacktoberfest-accepted

#66 Update script.js
  script.js
Labels: enhancement, hacktoberfest, Hacktoberfest-accepted

#68 Changed the twitter logo to latest
  index.html
Labels: enhancement, hacktoberfest, Hacktoberfest-accepted

#70 Added a web development project
  .vscode/settings.json
  images/project-images/todo.png
  index.html
Labels: hacktoberfest, Hacktoberfest-accepted

#69 I created 4 cards with provide with my git login form link.
  images/Thumbs.db
  images/project-images/Thumbs.db
  images/project-images/image2.jpg
  images/project-images/img 1.jpg
  images/project-images/login.png
  index.html
Labels: hacktoberfest, Hacktoberfest-accepted

#73 Contribution blood bank Django project
  contributors.md
  images/project-images/ubb.png
  index.html
Labels: hacktoberfest, Hacktoberfest-accepted, Project-addition

#76 Add a marvel music player project without merge conflicts from main
  contributors.md
  images/project-images/marvel-music-player.png
  index.html
Labels: hacktoberfest, Hacktoberfest-accepted, Project-addition

#77 Added Background-Color-chnaging-Project
  images/project-images/Background.png
  index.html
Labels: good first issue, hacktoberfest, Project-addition

#79 Chef Bakery Web Page
  images/project-images/bake.png
  index.html
Labels: hacktoberfest, Hacktoberfest-accepted, Project-addition

#80 Pendulum Animation
  contributors.md
  images/project-images/pendulum.png
  index.html
Labels: hacktoberfest, Hacktoberfest-accepted, Project-addition
